### ISSUE TITLE
Config comments are unlocalized

### ISSUE THREAD

**Issue by NielsPilgaard** [ChiselsAndBits/Chisels-and-Bits#522]
Comments/descriptions in the configs aren't localized, so they're aren't very helpful :P

Side question, is it possible to disable the `Chiseling: Supported` tooltip on supported blocks?

For any bug reports please provide the following details as well,
* MC Version: 1.16.3
* C&B Version: chiselsandbits-0.2.2-ALPHA
* Do You have Optifine: No

**Comment by NielsPilgaard** [comment]
This is still an issue. The configs are... in a weird place at the moment. Here's a little exert:

```toml
[server.server.server.server]

	#chiselsandbits.config.server.performance.comment
	[server.server.server.server.performance]

		[server.server.server.server.performance.server]

			[server.server.server.server.performance.server.performance]

				[server.server.server.server.performance.server.performance.memory]

					[server.server.server.server.performance.server.performance.memory.low-mode]
						#chiselsandbits.config.server.performance.memory.low-mode.enabled.comment
						enabled = false
```
